export const collectionNames = {
  users: "users",
  appointments: "appointments",
  doctors: "doctors",
  serviceRooms: "serviceRooms",
  hospital: "hospital",
};

export const queryKeys = {
  users: "users",
  appointments: "appointments",
  doctors: "doctors",
  serviceRooms: "serviceRooms",
  hospital: "hospital",
};

export const medicalSpecialtiesList = [
  "Alergologia",
  "Anestesiologia",
  "Angiologia",
  "Cancerologia (Oncologia)",
  "Cardiologia",
  "Cirurgia Cardiovascular",
  "Cirurgia da Mão",
  "Cirurgia de Cabeça e Pescoço",
  "Cirurgia do Aparelho Digestivo",
  "Cirurgia Geral",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Clínica Médica (Medicina Interna)",
  "Coloproctologia (Proctologia)",
  "Dermatologia",
  "Endocrinologia e Metabologia",
  "Endoscopia",
  "Gastroenterologia",
  "Genética Médica",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia e Hemoterapia",
  "Homeopatia",
  "Infectologia",
  "Mastologia",
  "Medicina de Família e Comunidade",
  "Medicina do Trabalho",
  "Medicina Esportiva",
  "Medicina Física e Reabilitação (Fisiatria)",
  "Medicina Intensiva",
  "Medicina Legal e Perícia Médica",
  "Medicina Nuclear",
  "Medicina Preventiva e Social",
  "Nefrologia",
  "Neurocirurgia",
  "Neurologia",
  "Nutrologia",
  "Oftalmologia",
  "Oncologia Clínica",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Patologia",
  "Patologia Clínica/Medicina Laboratorial",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Radiologia e Diagnóstico por Imagem",
  "Radioterapia",
  "Reumatologia",
  "Urologia",
];

export const genderList = [
  { id: "male", label: "Masculino" },
  { id: "female", label: "Feminino" },
  { id: "non_binary", label: "Não binário" },
  { id: "prefer_not_say", label: "Prefiro não dizer" },
  { id: "other", label: "Outro" },
];
